// tests/browser/structured-data.spec.js — JSON-LD that Google actually reads.
//
// BreadcrumbList is the one that changes what a search result LOOKS like:
// without it Google prints the bare URL instead of Home › PDF tools › Merge PDF.
// It is generated by scripts/gen-breadcrumbs.mjs from the tool manifest, so the
// real risk is drift — a new tool with no trail, or a trail pointing at a
// category page that does not exist.
import { test, expect } from '@playwright/test';
import { liveTools } from '../../shared/tools.js';
import { breadcrumbPlan } from '../../scripts/gen-breadcrumbs.mjs';

const ORIGIN = 'https://noadstools.com';

async function jsonLd(page, url) {
  await page.goto(url);
  return page.locator('script[type="application/ld+json"]')
    .evaluateAll((els) => els.map((e) => JSON.parse(e.textContent)));
}

for (const [file, trail] of breadcrumbPlan()) {
  const url = '/' + file.replace(/index\.html$/, '').replace(/^privacy\.html$/, 'privacy');

  test(`${url} has a BreadcrumbList matching the site hierarchy`, async ({ page }) => {
    const blocks = await jsonLd(page, url);
    const bc = blocks.find((b) => b['@type'] === 'BreadcrumbList');
    expect(bc, 'no BreadcrumbList (run: node scripts/gen-breadcrumbs.mjs)').toBeTruthy();

    // Positions must start at 1 and increment, or Google discards the trail.
    const positions = bc.itemListElement.map((i) => i.position);
    expect(positions).toEqual(trail.map((_, i) => i + 1));

    expect(bc.itemListElement.map((i) => i.name)).toEqual(trail.map((t) => t.name));
    expect(bc.itemListElement.map((i) => i.item)).toEqual(trail.map((t) => ORIGIN + t.path));
    expect(bc.itemListElement[0].name).toBe('Home');
  });
}

test('every breadcrumb target is a page that actually exists', async ({ request }) => {
  // A trail pointing at a 404 is worse than no trail.
  const targets = new Set();
  for (const [, trail] of breadcrumbPlan()) {
    for (const t of trail) targets.add(t.path);
  }
  for (const path of targets) {
    const res = await request.get(path);
    expect(res.status(), `breadcrumb links to ${path}`).toBe(200);
  }
});

test('every live tool page is covered by the breadcrumb generator', async () => {
  const covered = new Set([...breadcrumbPlan().keys()]);
  const missing = liveTools()
    .map((t) => `${t.slug}/index.html`)
    .filter((f) => !covered.has(f));
  expect(missing, 'run: node scripts/gen-breadcrumbs.mjs').toEqual([]);
});

test('tool pages keep their SoftwareApplication data alongside the breadcrumb', async ({ page }) => {
  // Adding a second JSON-LD block must not have displaced the first.
  const blocks = await jsonLd(page, '/merge-pdf/');
  const app = blocks.find((b) => /^(Software|Web)Application$/.test(b['@type']));
  expect(app, 'SoftwareApplication JSON-LD went missing').toBeTruthy();
  expect(app.offers.price).toBe('0');
});

test('the homepage still declares WebSite', async ({ page }) => {
  const blocks = await jsonLd(page, '/');
  expect(blocks.some((b) => b['@type'] === 'WebSite')).toBe(true);
});
