// scripts/publish.mjs
//
// Syncs the public-facing subset of this repo into a sibling folder
// (default: ../noadstools-public/) for publishing to the public GitHub repo
// (Dan512/NoAdsTools), which Cloudflare Pages serves.
//
// Excludes private project-management docs (CLAUDE.md, .impeccable.md,
// docs/, .claude/) so they never reach the public repo or its history.
//
// Tool directories are driven by shared/tools.js: every status:'live' tool's
// directory is included (a missing dir for a live tool is a HARD ERROR — see
// TOOL_DIRS below), so adding a tool to the platform = flipping its manifest
// status once its directory exists.
//
// Usage:
//   node scripts/publish.mjs                              # uses default dest
//   PUBLIC_PATH=/some/other/path node scripts/publish.mjs # custom dest
//   node scripts/publish.mjs --dry-run                    # preview, no writes

import { rm, mkdir, copyFile, readdir, stat, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join, dirname, relative, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { TOOLS } from '../shared/tools.js';

const SRC = process.cwd();
const DEST = resolve(process.env.PUBLIC_PATH ?? join(SRC, '..', 'noadstools-public'));
const DRY = process.argv.includes('--dry-run');
// Cloudflare Pages rejects any single file over 25 MiB.
const MAX_FILE_BYTES = 25 * 1024 * 1024;

// ---------------------------------------------------------------------------
// What gets published. Anything not in this list is excluded.
// Directories end with '/'. Files don't.
// ---------------------------------------------------------------------------
// Manifest-driven tool dirs: a missing dir for a status:'live' tool is an
// ERROR (the homepage links it and the wipe would delete it from the public
// repo) — fail loudly instead of skipping. Static INCLUDE entries keep the
// benign skip-missing behavior.
const TOOL_DIRS = new Set(TOOLS.filter(t => t.status === 'live').map(t => `${t.slug}/`));

const INCLUDE = [
  // Platform root (homepage + site files)
  'index.html',
  'home.css',
  'home.js',
  '404.html',
  'robots.txt',
  'sitemap.xml',
  'LICENSE',
  'README.md',
  'THIRD-PARTY.md',
  'vendor/',

  // The shared shell (AGPL corresponding source, incl. its tests + harness)
  'shared/',

  // Dev tooling (contributor onboarding + corresponding source)
  'package.json',
  'package-lock.json',
  'playwright.config.js',
  '.nvmrc',
  'scripts/serve.js',
  'scripts/install-bgremove.mjs',
  'scripts/install-heic.mjs',
  'scripts/install-ort.mjs',
  'scripts/install-tesseract.mjs',
  'scripts/install-blazeface.mjs',
  'scripts/publish.mjs',
  'tests/',

  // Tool directories — appended from shared/tools.js below.
  ...TOOL_DIRS,
];

// ---------------------------------------------------------------------------
// Hard excludes. Even if a parent is included, these never get copied.
// ---------------------------------------------------------------------------
const EXCLUDE = [
  // Private project-management
  'CLAUDE.md',
  '.impeccable.md',
  'AGENTS.md',
  '.agents/',
  'docs/',

  // Local-only state
  '.claude/',
  '.git/',
  '.tmp-vendor/',
  '.tmp/',
  'tmp/',
  'node_modules/',
  'playwright-report/',
  'test-results/',
  'coverage/',

  // OS junk
  '.DS_Store',
  'Thumbs.db',
  'Desktop.ini',
];

// ---------------------------------------------------------------------------
// Public-folder .gitignore. Slimmer than the private one (no need to ignore
// private project docs — they're never copied in).
// ---------------------------------------------------------------------------
export const PUBLIC_GITIGNORE = `# Public mirror — generated by scripts/publish.mjs from the working repo.
# Anything checked-in here is intended for public distribution under AGPL-3.0.

# Node / npm
node_modules/
npm-debug.log*
yarn-debug.log*
yarn-error.log*
.npm/

# Tests / coverage
playwright-report/
test-results/
playwright/.cache/
coverage/

# Linter / formatter caches
.eslintcache
.stylelintcache
.prettiercache
.cache/

# Build (defensive) — anchored to the mirror ROOT so a bare "build"/"dist"/"out"
# rule can never swallow a nested vendored directory. (A vendored lib ships its
# own build/ — e.g. vendor/pdfjs/legacy/build/pdf.min.mjs — and an unanchored
# "build/" rule silently dropped it from the push, 404ing the PDF engine.)
/dist/
/build/
/out/

# Logs / scratch / backup
*.log
*.tmp
*.bak
*.orig
*.rej
.tmp/
tmp/

# Secrets (defense in depth)
.env
.env.*
!.env.example
*.pem
*.key

# OS junk
.DS_Store
Thumbs.db
Desktop.ini

# Editors
.idea/
.vscode/settings.json
*.swp
*~
`;

// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Guard: which COPIED files would the mirror's own .gitignore exclude?
//
// publish.mjs copies files into the mirror, but the deploy actually ships
// whatever `git add` stages there — so a .gitignore rule that matches a copied
// file silently drops it from production. That is exactly how a bare `build/`
// rule once swallowed vendor/pdfjs/legacy/build/pdf.min.mjs → 404 → the PDF
// tools showed "corrupt PDF" for every file. This predicts that class of drop
// so the publish fails loudly instead.
//
// Supports the rule shapes PUBLIC_GITIGNORE actually emits:
//   name/      dir rule, matches a dir named `name` at ANY depth
//   /name/     anchored dir rule, matches `name/` only at the mirror root
//   a/b/ a/b   rooted path (has a slash) — matched from the root
//   *.ext name no-slash file/name glob — matches a path COMPONENT at any depth
//   !pattern   negation (un-ignore); last matching rule wins (git semantics)
// Globs support `*` and `?` within one path segment.
function segGlobToRegExp(glob) {
  let re = '';
  for (const ch of glob) {
    if (ch === '*') re += '[^/]*';
    else if (ch === '?') re += '[^/]';
    else re += ch.replace(/[.+^${}()|[\]\\]/g, '\\$&');
  }
  return new RegExp('^' + re + '$');
}

function parseIgnoreRules(text) {
  const rules = [];
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.replace(/\s+$/, '');
    if (!line || line.startsWith('#')) continue;
    let body = line;
    let negate = false;
    if (body.startsWith('!')) { negate = true; body = body.slice(1); }
    const dir = body.endsWith('/');
    if (dir) body = body.slice(0, -1);
    let anchored = body.startsWith('/');
    if (anchored) body = body.slice(1);
    const rooted = anchored || body.includes('/'); // matched from the root
    rules.push({ negate, dir, rooted, path: body, lastSeg: segGlobToRegExp(body.split('/').pop()) });
  }
  return rules;
}

// Does one rule apply to a path? `asDir` = treat the path as a directory (so a
// trailing-slash dir rule can match it). A dir-only rule NEVER matches a file
// (`build/` does not ignore a file literally named `build`).
function ruleAppliesTo(rule, path, segs, asDir) {
  if (rule.dir && !asDir) return false;
  if (rule.rooted) return path === rule.path || path.startsWith(rule.path + '/');
  // Unanchored single-segment glob: matches any path COMPONENT at any depth.
  for (const seg of segs) if (rule.lastSeg.test(seg)) return true;
  return false;
}

// Evaluate one path against all rules, last-match-wins. `asDir` toggles dir-rule
// matching (true for an ancestor directory, false for the file itself).
function evalIgnored(rules, path, segs, asDir) {
  let ignored = false;
  for (const rule of rules) if (ruleAppliesTo(rule, path, segs, asDir)) ignored = !rule.negate;
  return ignored;
}

/**
 * @param {string} gitignoreText the mirror .gitignore contents
 * @param {string[]} relPaths repo-relative paths that publish copied in
 * @returns {string[]} the copied paths the .gitignore would exclude
 *
 * Mirrors git's hierarchy: git evaluates directory-by-directory and never
 * descends into an excluded directory, so **a `!` negation cannot re-include a
 * file whose parent directory is excluded** (e.g. `.cache/` + `!.env.example`
 * still drops `.cache/.env.example`). We therefore check ancestor directories
 * first and only fall back to the file's own rules when no ancestor is excluded.
 */
export function gitignoredPublishedPaths(gitignoreText, relPaths) {
  const rules = parseIgnoreRules(gitignoreText);
  const hits = [];
  for (const raw of relPaths) {
    const rel = String(raw).split(/[\\/]/).join('/').replace(/^\/+/, '');
    if (!rel) continue;
    const segs = rel.split('/');
    let ignored = false;
    // 1) If any ancestor directory is excluded, the file is dropped — full stop.
    for (let k = 0; k < segs.length - 1; k++) {
      const dirSegs = segs.slice(0, k + 1);
      if (evalIgnored(rules, dirSegs.join('/'), dirSegs, true)) { ignored = true; break; }
    }
    // 2) No excluded ancestor → the file's own rules decide (negations can win).
    if (!ignored) ignored = evalIgnored(rules, rel, segs, false);
    if (ignored) hits.push(rel);
  }
  return hits;
}

// ---------------------------------------------------------------------------

function log(...args) { console.log(...args); }
function logDry(...args) { if (DRY) console.log('[dry]', ...args); else console.log(...args); }

function isExcluded(relPath) {
  // Normalize to forward slashes for matching.
  const norm = relPath.split(/[\\/]/).join('/');
  for (const ex of EXCLUDE) {
    const exNorm = ex;
    // Directory prefix match
    if (exNorm.endsWith('/') && (norm === exNorm.slice(0, -1) || norm.startsWith(exNorm))) return true;
    // Exact-name match (file or directory leaf)
    if (norm === exNorm || norm.endsWith('/' + exNorm)) return true;
  }
  return false;
}

async function copyTree(srcDir, destDir, files) {
  let copied = 0, skipped = 0;
  const entries = await readdir(srcDir, { withFileTypes: true });
  for (const e of entries) {
    const srcPath = join(srcDir, e.name);
    const destPath = join(destDir, e.name);
    const rel = relative(SRC, srcPath);
    if (isExcluded(rel) || isExcluded(rel + '/')) { skipped++; continue; }
    if (e.isDirectory()) {
      if (!DRY) await mkdir(destPath, { recursive: true });
      const sub = await copyTree(srcPath, destPath, files);
      copied += sub.copied;
      skipped += sub.skipped;
    } else if (e.isFile()) {
      if (!DRY) await copyFile(srcPath, destPath);
      if (files) files.push(rel);
      copied++;
    }
  }
  return { copied, skipped };
}

async function pathExistsAndIsFile(p) {
  try { const s = await stat(p); return s.isFile(); } catch { return false; }
}

async function pathExistsAndIsDir(p) {
  try { const s = await stat(p); return s.isDirectory(); } catch { return false; }
}

async function wipeDestExceptGit() {
  if (!existsSync(DEST)) {
    if (!DRY) await mkdir(DEST, { recursive: true });
    logDry(`created ${DEST}`);
    return;
  }
  const entries = await readdir(DEST);
  for (const name of entries) {
    if (name === '.git') continue; // preserve the public repo's git history
    const p = join(DEST, name);
    if (!DRY) await rm(p, { recursive: true, force: true });
    logDry(`removed ${name}`);
  }
}

async function main() {
  log(`Source: ${SRC}`);
  log(`Dest:   ${DEST}${DRY ? '  (dry run)' : ''}`);
  log('');

  // Safety: never wipe the working repo itself (a mistyped PUBLIC_PATH), and
  // only run from the repo root (SRC is cwd; a wrong cwd would "skip" everything).
  if (DEST === SRC || DEST.startsWith(SRC + '\\') || DEST.startsWith(SRC + '/')) {
    console.error(`ERROR: dest (${DEST}) is inside the source repo — refusing to wipe.`);
    process.exit(1);
  }
  if (!existsSync(join(SRC, 'index.html')) || !existsSync(join(SRC, 'shared'))) {
    console.error('ERROR: run from the repo root (index.html / shared/ not found in cwd).');
    process.exit(1);
  }

  await wipeDestExceptGit();

  let totalCopied = 0;
  let totalSkipped = 0;
  const publishedFiles = []; // mirror-relative paths, for the .gitignore guard

  for (const item of INCLUDE) {
    const srcPath = join(SRC, item.endsWith('/') ? item.slice(0, -1) : item);
    const destPath = join(DEST, item.endsWith('/') ? item.slice(0, -1) : item);
    const isDir = item.endsWith('/');

    if (isDir) {
      if (!(await pathExistsAndIsDir(srcPath))) {
        if (TOOL_DIRS.has(item)) {
          console.error(`ERROR: live tool directory missing: ${item} (fix shared/tools.js status or restore the dir)`);
          process.exit(1);
        }
        log(`skip (missing dir): ${item}`);
        continue;
      }
      if (!DRY) await mkdir(destPath, { recursive: true });
      const r = await copyTree(srcPath, destPath, publishedFiles);
      totalCopied += r.copied;
      totalSkipped += r.skipped;
      log(`copied ${r.copied} files from ${item}  (${r.skipped} skipped)`);
    } else {
      if (!(await pathExistsAndIsFile(srcPath))) {
        log(`skip (missing file): ${item}`);
        continue;
      }
      if (!DRY) {
        await mkdir(dirname(destPath), { recursive: true });
        await copyFile(srcPath, destPath);
      }
      publishedFiles.push(item);
      totalCopied++;
      log(`copied ${item}`);
    }
  }

  // Public .gitignore (overwrites whatever was there).
  if (!DRY) await writeFile(join(DEST, '.gitignore'), PUBLIC_GITIGNORE, 'utf8');
  log(`wrote .gitignore (public version)`);

  // Guard: the deploy ships what `git add` stages in the mirror, so a .gitignore
  // rule matching a COPIED file silently drops it from production (a bare
  // `build/` once did this to the vendored pdf.js engine → 404). Fail loudly
  // rather than push a mirror that is missing assets. Runs in dry mode too, so
  // `npm run publish:dry` catches it before any real publish.
  const ignoredPublished = gitignoredPublishedPaths(PUBLIC_GITIGNORE, publishedFiles);
  if (ignoredPublished.length) {
    console.error(`ERROR: ${ignoredPublished.length} copied file(s) are excluded by the mirror .gitignore — they would 404 in production:`);
    for (const f of ignoredPublished) console.error('  ' + f);
    console.error('Fix the offending rule in PUBLIC_GITIGNORE (e.g. anchor a build-output dir with a leading slash: `/build/`).');
    process.exit(1);
  }
  log(`gitignore guard: OK (${publishedFiles.length} published files, none excluded by the mirror .gitignore)`);

  // Deploy-integrity: the engines are LAZY same-origin modules, so an ABSENT
  // one produces no build error — the tool just 404s at runtime ("corrupt PDF").
  // The gitignore guard only catches "copied but ignored"; it can't catch
  // "referenced but never copied" (e.g. an untracked file lost to a fresh clone
  // / `git clean`, since it isn't on disk to copy). Assert the load-bearing
  // engine files are actually present in the mirror.
  const REQUIRED_PRESENT = [
    'vendor/pdfjs/legacy/build/pdf.min.mjs',       // pdf.js engine (sign/pdf-to-jpg/pdf-to-text)
    'vendor/pdfjs/legacy/build/pdf.worker.min.mjs', // pdf.js worker (same build/ dir)
    'vendor/pdf-lib/pdf-lib.esm.min.js',            // pdf-lib (merge/split/watermark/sign)
  ];
  const publishedSet = new Set(publishedFiles.map((p) => p.split(/[\\/]/).join('/')));
  const missingRequired = REQUIRED_PRESENT.filter((p) => !publishedSet.has(p));
  if (missingRequired.length) {
    console.error(`ERROR: ${missingRequired.length} required engine asset(s) were not published (absent from the working tree — a fresh clone/clean drops git-untracked files):`);
    for (const f of missingRequired) console.error('  ' + f);
    console.error('Restore them and ensure they are TRACKED in git before publishing.');
    process.exit(1);
  }
  log(`required-asset check: OK (${REQUIRED_PRESENT.length} engine files present)`);

  // Cloudflare Pages hard-caps single files at 25 MiB. Fail loudly if any
  // published file exceeds it (fallback if one ever does: serve it from R2).
  const oversize = [];
  async function scanSize(dir) {
    for (const e of await readdir(dir, { withFileTypes: true })) {
      if (e.name === '.git') continue;
      const p = join(dir, e.name);
      if (e.isDirectory()) await scanSize(p);
      else if (e.isFile()) {
        const s = await stat(p);
        if (s.size > MAX_FILE_BYTES) oversize.push(`${relative(DEST, p)} (${(s.size / 1048576).toFixed(1)} MiB)`);
      }
    }
  }
  if (!DRY) {
    await scanSize(DEST);
    if (oversize.length) {
      console.error(`ERROR: ${oversize.length} file(s) exceed Cloudflare Pages' 25 MiB cap:`);
      for (const f of oversize) console.error('  ' + f);
      process.exit(1);
    }
    log('25 MiB per-file check: OK');
  }

  log('');
  log(`Summary: ${totalCopied} files copied, ${totalSkipped} excluded by EXCLUDE list`);
  log('');
  log('Next steps:');
  log(`  cd ${DEST}`);
  log('  # first time only:');
  log('  git init');
  log('  git remote add origin https://github.com/Dan512/NoAdsTools.git');
  log('  git branch -M main');
  log('  # every publish:');
  log('  git add -A');
  log('  git commit -m "<your message>"');
  log('  git push -u origin main');
}

// Run only when executed directly (`node scripts/publish.mjs`), not when a test
// imports the pure helpers above — importing must have no side effects.
if (import.meta.url === pathToFileURL(process.argv[1] || '').href) {
  main().catch(err => {
    console.error(err);
    process.exit(1);
  });
}
