// scripts/publish.mjs
//
// Syncs the public-facing subset of this repo into a sibling folder
// (default: ../noadstools-public/) for publishing to the public GitHub repo
// (Dan512/NoAdsTools), which Cloudflare Pages serves.
//
// Excludes private project-management docs (CLAUDE.md, .impeccable.md,
// docs/, .claude/) so they never reach the public repo or its history.
//
// Tool directories are driven by shared/tools.js: every status:'live' tool's
// directory is included (a missing dir for a live tool is a HARD ERROR — see
// TOOL_DIRS below), so adding a tool to the platform = flipping its manifest
// status once its directory exists.
//
// Usage:
//   node scripts/publish.mjs                              # uses default dest
//   PUBLIC_PATH=/some/other/path node scripts/publish.mjs # custom dest
//   node scripts/publish.mjs --dry-run                    # preview, no writes

import { rm, mkdir, copyFile, readdir, stat, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join, dirname, relative, resolve } from 'node:path';
import { TOOLS } from '../shared/tools.js';

const SRC = process.cwd();
const DEST = resolve(process.env.PUBLIC_PATH ?? join(SRC, '..', 'noadstools-public'));
const DRY = process.argv.includes('--dry-run');
// Cloudflare Pages rejects any single file over 25 MiB.
const MAX_FILE_BYTES = 25 * 1024 * 1024;

// ---------------------------------------------------------------------------
// What gets published. Anything not in this list is excluded.
// Directories end with '/'. Files don't.
// ---------------------------------------------------------------------------
// Manifest-driven tool dirs: a missing dir for a status:'live' tool is an
// ERROR (the homepage links it and the wipe would delete it from the public
// repo) — fail loudly instead of skipping. Static INCLUDE entries keep the
// benign skip-missing behavior.
const TOOL_DIRS = new Set(TOOLS.filter(t => t.status === 'live').map(t => `${t.slug}/`));

const INCLUDE = [
  // Platform root (homepage + site files)
  'index.html',
  'home.css',
  'home.js',
  '404.html',
  'robots.txt',
  'sitemap.xml',
  'LICENSE',
  'README.md',
  'THIRD-PARTY.md',

  // The shared shell (AGPL corresponding source, incl. its tests + harness)
  'shared/',

  // Dev tooling (contributor onboarding + corresponding source)
  'package.json',
  'package-lock.json',
  'playwright.config.js',
  '.nvmrc',
  'scripts/serve.js',
  'scripts/install-bgremove.mjs',
  'scripts/install-heic.mjs',
  'scripts/install-ort.mjs',
  'scripts/install-tesseract.mjs',
  'scripts/install-blazeface.mjs',
  'scripts/publish.mjs',
  'tests/',

  // Tool directories — appended from shared/tools.js below.
  ...TOOL_DIRS,
];

// ---------------------------------------------------------------------------
// Hard excludes. Even if a parent is included, these never get copied.
// ---------------------------------------------------------------------------
const EXCLUDE = [
  // Private project-management
  'CLAUDE.md',
  '.impeccable.md',
  'AGENTS.md',
  '.agents/',
  'docs/',

  // Local-only state
  '.claude/',
  '.git/',
  '.tmp-vendor/',
  '.tmp/',
  'tmp/',
  'node_modules/',
  'playwright-report/',
  'test-results/',
  'coverage/',

  // OS junk
  '.DS_Store',
  'Thumbs.db',
  'Desktop.ini',
];

// ---------------------------------------------------------------------------
// Public-folder .gitignore. Slimmer than the private one (no need to ignore
// private project docs — they're never copied in).
// ---------------------------------------------------------------------------
const PUBLIC_GITIGNORE = `# Public mirror — generated by scripts/publish.mjs from the working repo.
# Anything checked-in here is intended for public distribution under AGPL-3.0.

# Node / npm
node_modules/
npm-debug.log*
yarn-debug.log*
yarn-error.log*
.npm/

# Tests / coverage
playwright-report/
test-results/
playwright/.cache/
coverage/

# Linter / formatter caches
.eslintcache
.stylelintcache
.prettiercache
.cache/

# Build (defensive)
dist/
build/
out/

# Logs / scratch / backup
*.log
*.tmp
*.bak
*.orig
*.rej
.tmp/
tmp/

# Secrets (defense in depth)
.env
.env.*
!.env.example
*.pem
*.key

# OS junk
.DS_Store
Thumbs.db
Desktop.ini

# Editors
.idea/
.vscode/settings.json
*.swp
*~
`;

// ---------------------------------------------------------------------------

function log(...args) { console.log(...args); }
function logDry(...args) { if (DRY) console.log('[dry]', ...args); else console.log(...args); }

function isExcluded(relPath) {
  // Normalize to forward slashes for matching.
  const norm = relPath.split(/[\\/]/).join('/');
  for (const ex of EXCLUDE) {
    const exNorm = ex;
    // Directory prefix match
    if (exNorm.endsWith('/') && (norm === exNorm.slice(0, -1) || norm.startsWith(exNorm))) return true;
    // Exact-name match (file or directory leaf)
    if (norm === exNorm || norm.endsWith('/' + exNorm)) return true;
  }
  return false;
}

async function copyTree(srcDir, destDir) {
  let copied = 0, skipped = 0;
  const entries = await readdir(srcDir, { withFileTypes: true });
  for (const e of entries) {
    const srcPath = join(srcDir, e.name);
    const destPath = join(destDir, e.name);
    const rel = relative(SRC, srcPath);
    if (isExcluded(rel) || isExcluded(rel + '/')) { skipped++; continue; }
    if (e.isDirectory()) {
      if (!DRY) await mkdir(destPath, { recursive: true });
      const sub = await copyTree(srcPath, destPath);
      copied += sub.copied;
      skipped += sub.skipped;
    } else if (e.isFile()) {
      if (!DRY) await copyFile(srcPath, destPath);
      copied++;
    }
  }
  return { copied, skipped };
}

async function pathExistsAndIsFile(p) {
  try { const s = await stat(p); return s.isFile(); } catch { return false; }
}

async function pathExistsAndIsDir(p) {
  try { const s = await stat(p); return s.isDirectory(); } catch { return false; }
}

async function wipeDestExceptGit() {
  if (!existsSync(DEST)) {
    if (!DRY) await mkdir(DEST, { recursive: true });
    logDry(`created ${DEST}`);
    return;
  }
  const entries = await readdir(DEST);
  for (const name of entries) {
    if (name === '.git') continue; // preserve the public repo's git history
    const p = join(DEST, name);
    if (!DRY) await rm(p, { recursive: true, force: true });
    logDry(`removed ${name}`);
  }
}

async function main() {
  log(`Source: ${SRC}`);
  log(`Dest:   ${DEST}${DRY ? '  (dry run)' : ''}`);
  log('');

  // Safety: never wipe the working repo itself (a mistyped PUBLIC_PATH), and
  // only run from the repo root (SRC is cwd; a wrong cwd would "skip" everything).
  if (DEST === SRC || DEST.startsWith(SRC + '\\') || DEST.startsWith(SRC + '/')) {
    console.error(`ERROR: dest (${DEST}) is inside the source repo — refusing to wipe.`);
    process.exit(1);
  }
  if (!existsSync(join(SRC, 'index.html')) || !existsSync(join(SRC, 'shared'))) {
    console.error('ERROR: run from the repo root (index.html / shared/ not found in cwd).');
    process.exit(1);
  }

  await wipeDestExceptGit();

  let totalCopied = 0;
  let totalSkipped = 0;

  for (const item of INCLUDE) {
    const srcPath = join(SRC, item.endsWith('/') ? item.slice(0, -1) : item);
    const destPath = join(DEST, item.endsWith('/') ? item.slice(0, -1) : item);
    const isDir = item.endsWith('/');

    if (isDir) {
      if (!(await pathExistsAndIsDir(srcPath))) {
        if (TOOL_DIRS.has(item)) {
          console.error(`ERROR: live tool directory missing: ${item} (fix shared/tools.js status or restore the dir)`);
          process.exit(1);
        }
        log(`skip (missing dir): ${item}`);
        continue;
      }
      if (!DRY) await mkdir(destPath, { recursive: true });
      const r = await copyTree(srcPath, destPath);
      totalCopied += r.copied;
      totalSkipped += r.skipped;
      log(`copied ${r.copied} files from ${item}  (${r.skipped} skipped)`);
    } else {
      if (!(await pathExistsAndIsFile(srcPath))) {
        log(`skip (missing file): ${item}`);
        continue;
      }
      if (!DRY) {
        await mkdir(dirname(destPath), { recursive: true });
        await copyFile(srcPath, destPath);
      }
      totalCopied++;
      log(`copied ${item}`);
    }
  }

  // Public .gitignore (overwrites whatever was there).
  if (!DRY) await writeFile(join(DEST, '.gitignore'), PUBLIC_GITIGNORE, 'utf8');
  log(`wrote .gitignore (public version)`);

  // Cloudflare Pages hard-caps single files at 25 MiB. Fail loudly if any
  // published file exceeds it (fallback if one ever does: serve it from R2).
  const oversize = [];
  async function scanSize(dir) {
    for (const e of await readdir(dir, { withFileTypes: true })) {
      if (e.name === '.git') continue;
      const p = join(dir, e.name);
      if (e.isDirectory()) await scanSize(p);
      else if (e.isFile()) {
        const s = await stat(p);
        if (s.size > MAX_FILE_BYTES) oversize.push(`${relative(DEST, p)} (${(s.size / 1048576).toFixed(1)} MiB)`);
      }
    }
  }
  if (!DRY) {
    await scanSize(DEST);
    if (oversize.length) {
      console.error(`ERROR: ${oversize.length} file(s) exceed Cloudflare Pages' 25 MiB cap:`);
      for (const f of oversize) console.error('  ' + f);
      process.exit(1);
    }
    log('25 MiB per-file check: OK');
  }

  log('');
  log(`Summary: ${totalCopied} files copied, ${totalSkipped} excluded by EXCLUDE list`);
  log('');
  log('Next steps:');
  log(`  cd ${DEST}`);
  log('  # first time only:');
  log('  git init');
  log('  git remote add origin https://github.com/Dan512/NoAdsTools.git');
  log('  git branch -M main');
  log('  # every publish:');
  log('  git add -A');
  log('  git commit -m "<your message>"');
  log('  git push -u origin main');
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
